# Generated by Django 5.2.7 on 2025-10-19 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField(help_text='Unesite poštanski broj u opsegu od 10000 do 99999.', validators=[django.core.validators.MinValueValidator(10000, message='Poštanski broj mora biti jednak ili veći od 10000.'), django.core.validators.MaxValueValidator(99999, message='Poštanski broj mora biti jednak ili manji od 99999.')], verbose_name='Poštanski broj')),
                ('country', models.CharField(max_length=125)),
            ],
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
