# Generated by Django 5.2 on 2025-12-23 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_customer_delete_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='postal_code',
            field=models.IntegerField(help_text='Enter the postal code between 10000 and 99999', validators=[django.core.validators.MinValueValidator(10000, message='Poštanski broj mora biti jednak ili veći od 10000.'), django.core.validators.MaxValueValidator(99999, message='Poštanski broj mora biti jednak ili manji od 99999.')], verbose_name='Poštanski broj'),
        ),
    ]
